---
- name: Topic 02 - ping both hosts
  hosts: web
  gather_facts: false
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Show success message
      ansible.builtin.debug:
        msg: "Both servers responded"
