apiVersion: v1
kind: Pod
metadata:
  name: orbital-relay
  labels:
    app: orbital-relay
spec:
  containers:
    - name: web
      image: nginx:1.27-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: site
          mountPath: /usr/share/nginx/html
  volumes:
    - name: site
      configMap:
        name: orbital-site
