apiVersion: v1
kind: Pod
metadata:
  name: orbital-relay
  labels:
    app: orbital-relay
spec:
  containers:
    - name: web
      image: <ECR_REGISTRY>/orbital-relay:1.0
      imagePullPolicy: Always
      ports:
        - containerPort: 80
