apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbital-relay
  labels:
    app: orbital-relay
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 1
  selector:
    matchLabels:
      app: orbital-relay
  template:
    metadata:
      labels:
        app: orbital-relay
    spec:
      containers:
        - name: web
          image: learnwithraghu/ncc-workshop:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "150m"
              memory: "64Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
