pipeline {
    agent any

    environment {
        CODE_DIR = '/var/jenkins_code'
    }

    stages {
        stage('List Mounted Code') {
            steps {
                sh 'echo "Listing ${CODE_DIR}:"'
                sh 'ls -la "${CODE_DIR}"'
            }
        }
        stage('Read a File') {
            steps {
                sh 'cat "${CODE_DIR}/app.py"'
            }
        }
    }
}
