apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "document-search.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
