apiVersion: v1
kind: Service
metadata:
  name: document-search
  namespace: document-search
  labels:
    app: document-search
spec:
  type: ClusterIP
  selector:
    app: document-search
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      name: http
