pipeline {
    agent any

    stages {
        stage('Syntax Check') {
            steps {
                dir('python-app') {
                    sh 'python3 -m py_compile app.py test_app.py'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('python-app') {
                    sh 'python3 -m unittest -v'
                }
            }
        }
    }
}
